composer_dialog_button_icon:
  type: string
  default: "superscript"
  description: "Change Dialog button icon."
svg_icons: 
  default: "superscript"
  type: "list"
  list_type: "compact"
  description: "List of FontAwesome 5 icons used in this theme component."
put_in_popup_menu:
  type: bool
  default: true
  description: "Add the Dialog button to popup options menu. Uncheck this to put it to toolbar section."  
composer_dialog_button_group:
  default: insertions
  type: enum
  choices:
    - fontStyles
    - extras
  description: "Change Dialog button group position."
